### ISSUE TITLE
恢复的sql，主键id变成科学计数

### ISSUE THREAD

**Issue by hoplex** [LianjiaTech/lightning#2]
命令：
./lightning -user root -password XXXX -host 127.0.0.1 -port 3306 \
  -no-defaults \
 -event-types delete \
 -binlog-file mysql-bin.000017 > flashback.sql

结果：
DELETE FROM `lfcp_jsnd_web`.`lfcp_form_group_page_config` WHERE `id` = 9.897767764966606e+16 LIMIT 1;
DELETE FROM `lfcp_jsnd_web`.`lfcp_form_group_page_config` WHERE `id` = 9.897767764966605e+16 LIMIT 1;

**Comment by martianzhang** [comment]
![image](https://user-images.githubusercontent.com/1827047/139388670-53e99e7d-d92a-4893-bef2-ed56c98be7c3.png)

未复现
